language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake .. && make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "SeyYMbk2ypxkscOU3FH4ck613v+zOkY56gwdyW1eQklQkcvgQI0jI1FFIW2kPuWbf5Le/fg4KQCiyvqhtG0pgkFZtKjpl9abPDswq3WIZxpImRattnL9ZyZ9G2ear9uiOgeV7fa5TN+YUY16vwcbz5vYHahdW5tOY36mBxPAZSelKTBOv7aPRwsfC3DFn88ArAGWhP9SYtymxeNjEsOK0yGxWBVTnPRtH2UXnKHATpK27XUNKbiaWiuGa5e88iVVoLKG1mQk02p2kVkPtaeAdUVKb9mu3Uf+aPHzo1yC/dyk0hRRZJ7Vc9/eaOkUqdTml3eMiOzqA3lKbT/nvqF/fgZ9QIYPCecOiHULatqtzra5OTC3/GylIu39Hp8JL+w0wZepoClBs/b0I7XwKrlYQhwlZ79AYOfMyw5FRInqMZakYxE1Jc29OBk20fjMsOzoDBlPnbRfRstLMN+V7P4kLF0dhEYPmJE0m52sI/PVQpMI8QNBEvrbpEQdp4q6z4ySe1JWcWs7/ooPoEDAPd7vLOq8Qf24/t30KPmJi9Xf3MNIwf0CFiO/xUzME8aEyYpDX8V1HbOX+OVaY9Tjkj3cMj7fM1v9Gk8O2Ih5GKPOZscqP5MPTxBrUlKYNpgqOq9ZfiZGxGOVZRqBWAzyvX6Li/T2Y0iEepve0lh+jHV4EjI="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Darek7D/DSignal"
      description: "The small simple signal pipeline library."
    notification_email: darek7d@gmail.com
    build_command_prepend: "mkdir coverity && cd coverity && cmake .."
    build_command: "make"
    branch_pattern: coverity_scan
